# ReShape

In [1]:
import numpy as np
arr= np.random.randint(1,100, size =(10,5)) # Sample -10 , feature-5
arr


array([[ 9, 57, 78, 64,  4],
       [90, 72, 42, 85, 26],
       [24, 82, 69, 18, 58],
       [20,  8, 49, 39, 74],
       [19, 72, 20, 46, 70],
       [60, 23,  4, 42, 26],
       [78, 52, 67, 82, 87],
       [96, 68, 98,  6, 25],
       [60, 10, 58, 11, 90],
       [33, 92, 50,  3, 72]])

In [2]:
arr.shape

(10, 5)

In [8]:
b= arr.reshape(5,10)
b.shape

(5, 10)

In [10]:
b

array([[25, 99, 70, 77, 67, 34, 93, 24, 45, 44],
       [39, 87, 81, 85, 76,  1, 18, 83, 76, 33],
       [ 7, 43, 66, 83, 35, 92, 13, 13, 25, 74],
       [73, 57, 88, 59, 80, 76, 28, 28, 72, 19],
       [31, 30, 97, 85,  8, 47, 85, 40, 86, 39]])

# Flatten

In [12]:
b.flatten()


array([25, 99, 70, 77, 67, 34, 93, 24, 45, 44, 39, 87, 81, 85, 76,  1, 18,
       83, 76, 33,  7, 43, 66, 83, 35, 92, 13, 13, 25, 74, 73, 57, 88, 59,
       80, 76, 28, 28, 72, 19, 31, 30, 97, 85,  8, 47, 85, 40, 86, 39])

## col wise flatting

In [16]:
col_wise_flt = np.ravel(b,order='F')
print(col_wise_flt)

[25 39  7 73 31 99 87 43 57 30 70 81 66 88 97 77 85 83 59 85 67 76 35 80
  8 34  1 92 76 47 93 18 13 28 85 24 83 13 28 40 45 76 25 72 86 44 33 74
 19 39]


## row_flatting

In [17]:
row_wise_flt = np.ravel(b,order='C')
print(row_wise_flt)

[25 99 70 77 67 34 93 24 45 44 39 87 81 85 76  1 18 83 76 33  7 43 66 83
 35 92 13 13 25 74 73 57 88 59 80 76 28 28 72 19 31 30 97 85  8 47 85 40
 86 39]


# Concatanate

In [21]:
a = np.random.randint(1,10,size=(3,4)) #3 row , 4 col
b = np.random.randint(20,30,size=(3,4))

print(a)
print(b)

[[4 8 4 2]
 [3 5 5 9]
 [3 8 5 6]]
[[23 22 29 24]
 [25 25 23 26]
 [28 21 26 22]]


In [23]:
con_row =np.concatenate((a,b),axis=0) # row
con_row

array([[ 4,  8,  4,  2],
       [ 3,  5,  5,  9],
       [ 3,  8,  5,  6],
       [23, 22, 29, 24],
       [25, 25, 23, 26],
       [28, 21, 26, 22]])

In [24]:
con_col =np.concatenate((a,b),axis=1) #col
con_col

array([[ 4,  8,  4,  2, 23, 22, 29, 24],
       [ 3,  5,  5,  9, 25, 25, 23, 26],
       [ 3,  8,  5,  6, 28, 21, 26, 22]])

# Transpose

In [25]:
mat =np.random.randint(2,20,size=(3,2))
mat

array([[18, 12],
       [18,  8],
       [18, 11]])

In [26]:
mat.T

array([[18, 18, 18],
       [12,  8, 11]])

# Split

In [30]:
# array split

a = np.random.randint(1 ,10 , size =(10,))
print(a)
splitted_array = np.array_split(a,3)

print(splitted_array)



[2 5 8 6 9 7 8 6 2 2]
[array([2, 5, 8, 6]), array([9, 7, 8]), array([6, 2, 2])]


# Arithmatic_Mathmatic_Function

Arithmetic operations are applied element by element between arrays or between an array and a scalar.

In [31]:
# faster for vectorization

x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ])

add = np.add(x,y)
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

remainder = x % y

print(remainder)

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


## mathmatical function

# NumPy Mathematical Functions (Complete Note)

## 🔷 Definition

Mathematical functions in NumPy are built-in functions that perform element-wise mathematical operations on arrays. These functions are fast, efficient, and vectorized (no need for loops).

---

## 🔷 1. Basic Mathematical Functions

### Example:

```python
import numpy as np

a = np.array([1, 4, 9, 16])
```

### ➤ Square Root

```python
np.sqrt(a)
# Output: [1. 2. 3. 4.]
```

### ➤ Power

```python
np.power(a, 2)
# Output: [  1  16  81 256]
```

### ➤ Absolute Value

```python
np.abs([-1, -5, 3])
# Output: [1 5 3]
```

---

## 🔷 2. Exponential & Logarithmic Functions

### ➤ Exponential

```python
np.exp(a)
```

### ➤ Natural Logarithm (ln)

```python
np.log(a)
```

### ➤ Base-10 Log

```python
np.log10(a)
```

### ➤ Base-2 Log

```python
np.log2(a)
```

---

## 🔷 3. Trigonometric Functions

### Example:

```python
a = np.array([0, np.pi/2, np.pi])
```

### ➤ Sine

```python
np.sin(a)
# Output: [0. 1. 0.]
```

### ➤ Cosine

```python
np.cos(a)
# Output: [ 1.  0. -1.]
```

### ➤ Tangent

```python
np.tan(a)
```

---

## 🔷 4. Rounding Functions

### Example:

```python
a = np.array([1.2, 2.5, 3.7])
```

### ➤ Round

```python
np.round(a)
# Output: [1. 2. 4.]
```

### ➤ Floor

```python
np.floor(a)
# Output: [1. 2. 3.]
```

### ➤ Ceil

```python
np.ceil(a)
# Output: [2. 3. 4.]
```

### ➤ Truncate

```python
np.trunc(a)
# Output: [1. 2. 3.]
```

---

## 🔷 5. Statistical Mathematical Functions
# New Section
### Example:

```python
a = np.array([10,20,30,40])
```

```python
np.sum(a)    # 100
np.mean(a)   # 25
np.median(a) # 25
np.min(a)    # 10
np.max(a)    # 40
np.std(a)    # Standard deviation
np.var(a)    # Variance
```

---

## 🔷 6. Important Features

* All functions work **element-wise**
* No loops required (vectorized operations)
* Faster than normal Python
* Works on large datasets efficiently

---

## 🎯 Conclusion

NumPy mathematical functions provide powerful tools for performing fast and efficient numerical operations such as square root, logarithms, trigonometric calculations, rounding, and statistical analysis on arrays.


In [39]:
a=np.random.randint(1,100,size=(20))
a

array([74, 63, 48, 43, 48, 35, 61, 30, 28, 55, 11, 83, 37, 76, 53, 96,  7,
       80, 94, 42])

In [41]:
np.sum(a)

np.int64(1064)

In [42]:
np.mean(a)

np.float64(53.2)

In [43]:
np.median(a)

np.float64(50.5)

In [44]:
np.min(a)

np.int64(7)

In [45]:
np.max(a)

np.int64(96)

In [46]:
np.std(a)    # Standard deviation

np.float64(24.67914098991292)

In [47]:
np.var(a)

np.float64(609.0600000000001)

## Broadcasting

In [50]:
#broadcasting

x = np.array([ 10 , 8 , 16 , 100 ])

result = x + 2
result


array([ 12,  10,  18, 102])

In [48]:

#rulings = columns er size and vector er size same hote hobe

matrix = np.array([[10,20,30],
                [30,40,50]
               ])


result = matrix + 2

vector = np.array([2,3,4])

result = matrix +vector
print(result)

[[12 23 34]
 [32 43 54]]


# Logical_Function

In [51]:
# comparison - >,< , >= ,<= , == , !=

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ])

greater_than = x>y

print(greater_than)



[ True  True False  True]


In [52]:
equal = x==y

print(equal)

# all () -> shob true kina
# any() -> jekono ekta true ase kina

print(np.all(greater_than))

print(np.any(equal))

[False False  True False]
False
True


# Sorting

In [53]:
#inplace
x = np.array([ 10 , 8 , 16 , 100 ])

z = x.copy()

print(z)

z.sort()

print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [54]:
# copy sorting
print(x)
sort_arr = np.sort(x)

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [57]:
# 2d array sorting
mat = np.array([[10,3,5],[8,4,9]])

# horizon axis = 1

hor_sort = np.sort(mat,axis=1)
print(hor_sort)

[[ 3  5 10]
 [ 4  8  9]]


In [58]:
vert_sort = np.sort(mat,axis=0)
print(vert_sort)

[[ 8  3  5]
 [10  4  9]]


# Searching

In [3]:
a= np.random.randint(2,100,size=(80))
a

array([75, 81, 80, 73,  9, 33, 97, 74, 94, 99, 52, 70, 22, 74, 21, 56, 77,
       62, 99, 88, 42, 40, 77, 89, 21,  5, 91, 59, 26, 57, 34, 98, 77, 37,
       46,  3, 96, 59, 26, 15, 57, 91, 91, 64, 77, 31, 49, 32, 14, 98, 23,
       71, 66, 67, 60, 94, 87, 36, 24, 97, 49, 94, 14, 64, 20, 51, 53, 63,
       17, 91, 79, 83, 85, 99, 43,  4, 18, 76, 80, 69])

In [5]:
np.where(a==99)


(array([ 9, 18, 73]),)

In [6]:
np.where(a>30)


(array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 13, 15, 16, 17, 18, 19,
        20, 21, 22, 23, 26, 27, 29, 30, 31, 32, 33, 34, 36, 37, 40, 41, 42,
        43, 44, 45, 46, 47, 49, 51, 52, 53, 54, 55, 56, 57, 59, 60, 61, 63,
        65, 66, 67, 69, 70, 71, 72, 73, 74, 77, 78, 79]),)

**np.where(condition ,x,y) if ture x , otherwise replace with y**


In [8]:
index= np.where(a>30,a,0)
print(index)

[75 81 80 73  0 33 97 74 94 99 52 70  0 74  0 56 77 62 99 88 42 40 77 89
  0  0 91 59  0 57 34 98 77 37 46  0 96 59  0  0 57 91 91 64 77 31 49 32
  0 98  0 71 66 67 60 94 87 36  0 97 49 94  0 64  0 51 53 63  0 91 79 83
 85 99 43  0  0 76 80 69]


# NumPy Searching (Simple + Complete Note)

## 🔷 Definition

Searching in NumPy means finding **values, indices, or positions** of elements in an array. It helps locate data efficiently using conditions or built-in functions.

---

## 🔷 1. Using `np.where()`

Returns indices where a condition is true.

### Example:

```python
import numpy as np
a = np.array([10, 20, 30, 40])

np.where(a == 30)
# Output: (array([2]),)
```

### Condition:

```python
np.where(a > 20)
# Output: (array([2, 3]),)
```

### 2D Example:

```python
a = np.array([[1,2,3],
              [4,5,6]])

np.where(a > 3)
# Output: (array([1,1,1]), array([0,1,2]))
```

👉 Returns (row_indices, column_indices)

---

## 🔷 2. Using `np.searchsorted()`

Finds the position where a value should be inserted in a **sorted array**.

### Example:

```python
a = np.array([10,20,30,40])

np.searchsorted(a, 25)
# Output: 2
```

### Multiple values:

```python
np.searchsorted(a, [15,35])
# Output: [1 3]
```

### Left vs Right:

```python
a = np.array([10,20,20,30])

np.searchsorted(a, 20)              # 1
np.searchsorted(a, 20, side='right') # 3
```

👉 Array must be sorted

---

## 🔷 3. Using `np.argmax()` and `np.argmin()`

Find index of maximum and minimum value.

```python
a = np.array([10,50,30])

np.argmax(a)  # 1
np.argmin(a)  # 0
```

---

## 🔷 4. Using `np.nonzero()`

Returns indices of non-zero elements.

```python
a = np.array([0,1,2,0,3])

np.nonzero(a)
# Output: (array([1,2,4]),)
```

---

## 🔷 5. Boolean Searching (Filtering)

Returns values based on condition.

```python
a = np.array([10,20,30,40])

a[a > 20]
# Output: [30 40]
```

### Multiple conditions:

```python
a[(a > 10) & (a < 40)]
# Output: [20 30]
```

---

## 🔷 Key Points

* `where()` → returns indices
* `searchsorted()` → returns insertion position
* `argmax()` / `argmin()` → index of max/min
* `nonzero()` → indices of non-zero elements
* Boolean indexing → returns filtered values

---

## 🎯 Conclusion

NumPy searching provides efficient methods to locate elements, find positions, and filter data using conditions. It is essential for data analysis and array manipulation.


# Counting

In [25]:
a=np.random.randint(0,20,size=(70))
a

array([16, 19, 17, 11,  8,  3, 17, 15, 14,  7, 16,  8,  5,  0, 10, 15,  5,
       12, 13,  6,  3, 19, 18, 10,  4, 17,  1, 10,  4,  5,  5,  0,  6, 11,
        4, 15, 17,  5, 18,  8,  0, 15,  2,  4,  4, 19,  6,  6,  3, 11, 19,
        0, 12,  4,  5, 11, 16, 15,  2, 15,  4, 18, 13, 16, 12, 19,  6,  1,
       12, 18])

In [23]:
np.count_nonzero(a)

68

In [29]:
np.sum(a>10)

np.int64(29)

**unique value**

In [30]:
unique_value,count = np.unique(a,return_counts=True)

print(unique_value)
print(count)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[2 4 5 5 3 3 4 2 3 6 4 3 4 1 1 6 3 2 5 4]
