# Ufuncs

https://www.w3schools.com/python/numpy/numpy_ufunc.asp

## Ufunc creation

To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

1. function - the name of the function.


2. inputs - the number of input arguments (arrays).

3. outputs - the number of output arrays.


In [2]:
import numpy as np

In [5]:
def myadd(x,y):
  return x+y

myadd=np.frompyfunc(myadd,2,1)
print(myadd([1,2,3,4],[5,6,3,2]))


[6 8 6 6]


## Arithamtic_Operations

In [6]:
# ==============================
# NUMPY UFUNC ARITHMETIC (FULL)
# ==============================

import numpy as np

# ------------------------------
# 1. Create Arrays
# ------------------------------
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a =", a)
print("b =", b)

# ------------------------------
# 2. Addition
# ------------------------------
print("\nAddition:")
print(np.add(a, b))
print(a + b)

# ------------------------------
# 3. Subtraction
# ------------------------------
print("\nSubtraction:")
print(np.subtract(a, b))
print(a - b)

# ------------------------------
# 4. Multiplication
# ------------------------------
print("\nMultiplication:")
print(np.multiply(a, b))
print(a * b)

# ------------------------------
# 5. Division
# ------------------------------
print("\nDivision:")
print(np.divide(a, b))
print(a / b)

# ------------------------------
# 6. Power
# ------------------------------
print("\nPower:")
print(np.power(a, 2))
print(a ** 2)

# ------------------------------
# 7. Modulus
# ------------------------------
print("\nModulus:")
print(np.mod(a, 2))
print(a % 2)

# ------------------------------
# 8. Absolute
# ------------------------------
c = np.array([-1, -2, 3])
print("\nAbsolute:")
print(np.absolute(c))

# ------------------------------
# 9. Reciprocal
# ------------------------------
d = np.array([1.0, 2.0, 4.0])
print("\nReciprocal:")
print(np.reciprocal(d))

# ------------------------------
# 10. Negative
# ------------------------------
print("\nNegative:")
print(np.negative(a))

# ------------------------------
# 11. Floor Division
# ------------------------------
print("\nFloor Division:")
print(np.floor_divide(a, b))

# ------------------------------
# 12. Broadcasting
# ------------------------------
print("\nBroadcasting:")
print(np.add(a, 10))

# ------------------------------
# 13. 2D Array Operations
# ------------------------------
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print("\n2D Multiplication:")
print(np.multiply(x, y))

# ------------------------------
# 14. Reduce (Sum)
# ------------------------------
print("\nReduce (Sum):")
print(np.add.reduce(a))

# ------------------------------
# 15. Accumulate (Cumulative Sum)
# ------------------------------
print("\nAccumulate:")
print(np.add.accumulate(a))

# ------------------------------
# 16. Outer Product
# ------------------------------
print("\nOuter Product:")
print(np.multiply.outer(a, b))

a = [1 2 3]
b = [4 5 6]

Addition:
[5 7 9]
[5 7 9]

Subtraction:
[-3 -3 -3]
[-3 -3 -3]

Multiplication:
[ 4 10 18]
[ 4 10 18]

Division:
[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]

Power:
[1 4 9]
[1 4 9]

Modulus:
[1 0 1]
[1 0 1]

Absolute:
[1 2 3]

Reciprocal:
[1.   0.5  0.25]

Negative:
[-1 -2 -3]

Floor Division:
[0 0 0]

Broadcasting:
[11 12 13]

2D Multiplication:
[[ 5 12]
 [21 32]]

Reduce (Sum):
6

Accumulate:
[1 3 6]

Outer Product:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


## Rounding_Decimal

In [7]:
# =========================================
# NUMPY ROUNDING (COMPLETE SINGLE FILE)
# =========================================

import numpy as np

# -----------------------------------------
# 1. Create Sample Array
# -----------------------------------------
a = np.array([1.2345, 2.5678, 3.9999, -2.7, -3.5])

print("Original Array:")
print(a)

# -----------------------------------------
# 2. ROUND (Nearest Value)
# -----------------------------------------
print("\n1. ROUND (np.round)")
print("Round to 2 decimal places:")
print(np.round(a, 2))

print("\nBanker's Rounding Example:")
print("np.round(3.5) =", np.round(3.5))
print("np.round(2.5) =", np.round(2.5))

# -----------------------------------------
# 3. FLOOR (Always Down)
# -----------------------------------------
print("\n2. FLOOR (np.floor)")
print(np.floor(a))

# -----------------------------------------
# 4. CEIL (Always Up)
# -----------------------------------------
print("\n3. CEIL (np.ceil)")
print(np.ceil(a))

# -----------------------------------------
# 5. TRUNC (Remove Decimal)
# -----------------------------------------
print("\n4. TRUNC (np.trunc)")
print(np.trunc(a))

# -----------------------------------------
# 6. FIX (Towards Zero)
# -----------------------------------------
print("\n5. FIX (np.fix)")
print(np.fix(a))

# -----------------------------------------
# 7. Comparison Summary
# -----------------------------------------
print("\n6. COMPARISON TABLE")
print("Value\tRound\tFloor\tCeil\tTrunc")

for val in a:
    print(f"{val}\t{np.round(val)}\t{np.floor(val)}\t{np.ceil(val)}\t{np.trunc(val)}")

# -----------------------------------------
# 8. 2D ARRAY ROUNDING
# -----------------------------------------
b = np.array([[1.234, 2.789], [3.456, 4.999]])

print("\n7. 2D ARRAY ROUNDING")
print("Original:")
print(b)

print("\nRounded (2 decimals):")
print(np.round(b, 2))

# -----------------------------------------
# 9. PRACTICE SECTION
# -----------------------------------------
print("\n8. PRACTICE")

c = np.array([10.55, 20.25, 30.75])

print("Original:", c)
print("Round:", np.round(c))
print("Floor:", np.floor(c))
print("Ceil:", np.ceil(c))

# -----------------------------------------
# END
# -----------------------------------------
print("\n--- Done Learning Rounding in NumPy ---")

Original Array:
[ 1.2345  2.5678  3.9999 -2.7    -3.5   ]

1. ROUND (np.round)
Round to 2 decimal places:
[ 1.23  2.57  4.   -2.7  -3.5 ]

Banker's Rounding Example:
np.round(3.5) = 4.0
np.round(2.5) = 2.0

2. FLOOR (np.floor)
[ 1.  2.  3. -3. -4.]

3. CEIL (np.ceil)
[ 2.  3.  4. -2. -3.]

4. TRUNC (np.trunc)
[ 1.  2.  3. -2. -3.]

5. FIX (np.fix)
[ 1.  2.  3. -2. -3.]

6. COMPARISON TABLE
Value	Round	Floor	Ceil	Trunc
1.2345	1.0	1.0	2.0	1.0
2.5678	3.0	2.0	3.0	2.0
3.9999	4.0	3.0	4.0	3.0
-2.7	-3.0	-3.0	-2.0	-2.0
-3.5	-4.0	-4.0	-3.0	-3.0

7. 2D ARRAY ROUNDING
Original:
[[1.234 2.789]
 [3.456 4.999]]

Rounded (2 decimals):
[[1.23 2.79]
 [3.46 5.  ]]

8. PRACTICE
Original: [10.55 20.25 30.75]
Round: [11. 20. 31.]
Floor: [10. 20. 30.]
Ceil: [11. 21. 31.]

--- Done Learning Rounding in NumPy ---
